[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
poap_alyra = "D9cwyogXbCP7CfafmRGrkDe2acpSbzcgVng3Gzw6UP8L"

[programs.devnet]
poap_alyra = "D9cwyogXbCP7CfafmRGrkDe2acpSbzcgVng3Gzw6UP8L"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-init-0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/poap-alyra-init-0.ts"
test-init-1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/poap-alyra-init-1.ts"
test-init-2-plus = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/poap-alyra-init-2-plus.ts"

test-init-1-mint-1-plus = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/poap-alyra-init-1-mint-1-plus.ts"
test-init-0-mint-2-plus-delete-all-mint-2-plus = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/poap-alyra-init-0-mint-2-plus-delete-all-mint-2-plus.ts"
