import {
  ADDRESS_LENGTH,
  AIRDROP_DEFAULT_AMOUNT, AIRDROP_MAX_AMOUNT,
  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MAX_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
  NFT_COUNT_MAX,
  NFT_NAME_PREFIX_MAXLENGTH,
 } from "@consts/commons"

 const TOAST_SUCCESS_DELAY = 10_000
 const TOAST_WARN_DELAY = 15_000
 const TOAST_ERROR_DELAY = 30_000
 
 const MINT_URI_PATH = '/mint'

 // Page which displays the QR code to the Mint page
 const MINT_QR_URI_PATH = '/qr/displayQrToMintPage'

 // Page which displays the QR code for minting
 const DISPLAY_DIRECT_MINT_FROM_QR_URI_PATH = '/qr/displayDirectMintQr'

 // Page which calls the NFT minting API
 const DIRECT_MINT_FROM_QR_URI_PATH = '/directMintFromQr'

// Page which actually mints the NFT
const API_MINT_FREE_PATH = '/api/mint-free-qr'

const TOAST_POSITION = 'top-right'

export {
  AIRDROP_DEFAULT_AMOUNT,
  AIRDROP_MAX_AMOUNT,

  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  MINT_FEE_MAX_AMOUNT,

  NFT_COUNT_MAX,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
  NFT_NAME_PREFIX_MAXLENGTH,
  ADDRESS_LENGTH,

  TOAST_SUCCESS_DELAY,
  TOAST_WARN_DELAY,
  TOAST_ERROR_DELAY,
  TOAST_POSITION,

  MINT_URI_PATH,
  MINT_QR_URI_PATH,
  DISPLAY_DIRECT_MINT_FROM_QR_URI_PATH,
  DIRECT_MINT_FROM_QR_URI_PATH,
  API_MINT_FREE_PATH,
}
