import {
  ADDRESS_LENGTH,
  AIRDROP_DEFAULT_AMOUNT, AIRDROP_MAX_AMOUNT,
  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MAX_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
  NFT_COUNT_MAX,
  NFT_NAME_PREFIX_MAXLENGTH,
 } from "@consts/commons"

 const SUCCESS_DELAY = 10_000
 const WARN_DELAY = 15_000
 const ERROR_DELAY = 30_000
 
 const MINT_URI_PATH = '/mint'

export {
  AIRDROP_DEFAULT_AMOUNT,
  AIRDROP_MAX_AMOUNT,

  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  MINT_FEE_MAX_AMOUNT,

  NFT_COUNT_MAX,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
  NFT_NAME_PREFIX_MAXLENGTH,
  ADDRESS_LENGTH,

  SUCCESS_DELAY,
  WARN_DELAY,
  ERROR_DELAY,
 
  MINT_URI_PATH,
}
