import { SIGNATURE_LENGTH_IN_BYTES } from "@solana/web3.js"

const AIRDROP_DEFAULT_AMOUNT = 1
const AIRDROP_MAX_AMOUNT = 100

export {
  SIGNATURE_LENGTH_IN_BYTES,
  AIRDROP_DEFAULT_AMOUNT,
  AIRDROP_MAX_AMOUNT,
}

