import { SIGNATURE_LENGTH_IN_BYTES } from "@solana/web3.js"
import { NFT_NAME_PREFIX_MAX_LENGTH as NFT_NAME_PREFIX_MAX_LENGTH_MPLX } from "./mtplx"

const AIRDROP_DEFAULT_AMOUNT = 1 // 1 SOL
const AIRDROP_MAX_AMOUNT = 100 // 100 SOL
const MINT_FEE_DEFAULT_AMOUNT = 1 // 1 SOL
const MINT_FEE_MIN_AMOUNT = 0.001 // 1 SOL
const MINT_FEE_MAX_AMOUNT = 10 // 1 SOL

const NFT_COUNT_MAX = 100
const NFT_COLLECTION_SYMBOL_MAXLENGTH = 10
const NFT_NAME_PREFIX_MAXLENGTH = NFT_NAME_PREFIX_MAX_LENGTH_MPLX
const ADDRESS_LENGTH = 44

const MINT_URI_PATH = '/mint'


export {
  SIGNATURE_LENGTH_IN_BYTES,
  AIRDROP_DEFAULT_AMOUNT,
  AIRDROP_MAX_AMOUNT,

  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  MINT_FEE_MAX_AMOUNT,

  NFT_COUNT_MAX,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
  NFT_NAME_PREFIX_MAXLENGTH,
  ADDRESS_LENGTH,

  MINT_URI_PATH,
}
