import { SIGNATURE_LENGTH_IN_BYTES } from "@solana/web3.js"

const AIRDROP_DEFAULT_AMOUNT = 1 // 1 SOL
const AIRDROP_MAX_AMOUNT = 100 // 100 SOL
const MINT_FEE_DEFAULT_AMOUNT = 1 // 1 SOL
const MINT_FEE_MIN_AMOUNT = 0.001 // 1 SOL
const MINT_FEE_MAX_AMOUNT = 10 // 1 SOL

const NFT_COUNT_MAX = 100
const NFT_COLLECTION_SYMBOL_MAXLENGTH = 10


export {
  SIGNATURE_LENGTH_IN_BYTES,
  AIRDROP_DEFAULT_AMOUNT,
  AIRDROP_MAX_AMOUNT,

  MINT_FEE_DEFAULT_AMOUNT,
  MINT_FEE_MIN_AMOUNT,
  MINT_FEE_MAX_AMOUNT,

  NFT_COUNT_MAX,
  NFT_COLLECTION_SYMBOL_MAXLENGTH,
}
