import {
  MPL_F_sol
} from '@imports/mtplx.imports';

// balance(s)
const MINIMUM_CREATOR_BALANCE = 1 // 1 SOL
const LOW_CREATOR_BALANCE = 10 // 10 SOL

const NFT_NAME_PREFIX_MAX_LENGTH = 32

const MINIMUM_CREATOR_BALANCE_SOL = MPL_F_sol(MINIMUM_CREATOR_BALANCE)
const LOW_CREATOR_BALANCE_SOL = MPL_F_sol(LOW_CREATOR_BALANCE)

const URI_MAX_LENGTH = 140

export {
  MINIMUM_CREATOR_BALANCE,
  LOW_CREATOR_BALANCE,
  NFT_NAME_PREFIX_MAX_LENGTH,
  MINIMUM_CREATOR_BALANCE_SOL,
  LOW_CREATOR_BALANCE_SOL,
  URI_MAX_LENGTH
}